#Parameters for connecting to the database
DATABASE:
  port_db: '5432'
  local_db_ip: 'postgres'
  #'127.0.0.1'
  db_user:  'vim_admin'
  db_password: 'vim'
  db_name: 'telegram'
SETTINGS:
  threads: 3
  tg_limit: 2
  messages_limit: 200000
  messages_date_start: '2024-03-01'
LOGGING:
  logs_bot_token: '6733863104:AAE1QxUXUPmTACQfNlY8HdLcLOT4iMxvy3U'
  logs_group_id: -1002093059669
  log_file: 'spider.log'
